global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "chat-service"
    static_configs:
      - targets: ["chat-service:8000"]
    scrape_interval: 5s
    metrics_path: '/metrics'